#!/usr/bin/env python3
"""Regenerate the knowledge bundle's index.md from concept frontmatter.

The listing below the marker line in docs/knowledge/index.md is generated,
never hand-edited (OKF invariant: indexes are generated). The preamble above
the marker is the bundle's local law and stays hand-written.

Usage:
    python3 scripts/kb_index.py           # rewrite index.md in place
    python3 scripts/kb_index.py --check   # exit 1 if index.md is stale

Fails the run (and the pre-commit hook) on: a concept without parseable
frontmatter; a missing or empty type, title, description, or generated
field; a type outside its folder's declared set.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "docs" / "knowledge"
MARKER = "<!-- generated by scripts/kb_index.py - edit concepts, not this listing -->"

# folder -> (required type, section heading), in index order
FOLDERS = [
    ("decisions", "Decision", "Decisions"),
    ("findings", "Finding", "Findings"),
    ("references", "Reference", "References"),
]

REQUIRED = ("type", "title", "description", "generated")


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        sys.exit(f"kb_index: {path}: no frontmatter block")
    fields: dict[str, str] = {}
    key = None
    for line in m.group(1).splitlines():
        top = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
        if top:
            key = top.group(1)
            fields[key] = top.group(2).strip()
        elif key and line.startswith(" ") and not line.lstrip().startswith("-"):
            # folded continuation of a scalar value
            fields[key] = (fields[key] + " " + line.strip()).strip()
    return fields


def build_listing() -> str:
    sections = []
    for folder, required_type, heading in FOLDERS:
        entries = []
        for f in sorted((ROOT / folder).glob("*.md")):
            meta = frontmatter(f)
            for field in REQUIRED:
                if not meta.get(field):
                    sys.exit(f"kb_index: {f}: missing or empty '{field}'")
            if meta["type"] != required_type:
                sys.exit(
                    f"kb_index: {f}: type '{meta['type']}' outside the "
                    f"'{folder}/' set ({required_type})"
                )
            title = meta["title"].strip("\"'")
            desc = meta["description"].strip("\"'")
            suffix = " (deprecated)" if meta.get("status") == "deprecated" else ""
            entries.append(f"* [{title}]({folder}/{f.name}) - {desc}{suffix}")
        if entries:
            sections.append(f"# {heading}\n\n" + "\n".join(entries))
    return "\n\n".join(sections) + "\n"


def main() -> None:
    index = ROOT / "index.md"
    text = index.read_text(encoding="utf-8")
    if MARKER not in text:
        sys.exit(f"kb_index: {index}: marker line missing; refusing to guess the preamble")
    head = text.split(MARKER)[0]
    fresh = head + MARKER + "\n\n" + build_listing()
    if "--check" in sys.argv:
        if text != fresh:
            sys.exit("kb_index: index.md is stale - run: python3 scripts/kb_index.py")
        print("kb_index: index.md is current")
        return
    index.write_text(fresh, encoding="utf-8")
    print(f"kb_index: wrote {index}")


if __name__ == "__main__":
    main()
